USE ImageAppDB;

CREATE TABLE USER (
	USER_ID INT PRIMARY KEY,
    USER_EMAIL VARCHAR(255) UNIQUE,
    USER_PASSWORD VARCHAR(255),
    FISRT_NAME VARCHAR(255)
) ENGINE=INNODB;

CREATE TABLE IMAGE(
	IMAGE_ID INT PRIMARY KEY,
    IMG TEXT,
    IMAGE_NAME TEXT NOT NULL,
    MIMETYPE TEXT NOT NULL,
    USER_ID INT,
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
) ENGINE=INNODB;

CREATE TABLE POST(
	POST_ID INT PRIMARY KEY,
    POST_NOTE VARCHAR(255),
    USER_ID INT,
    IMAGE_ID INT,
    FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY(IMAGE_ID) REFERENCES IMAGE(IMAGE_ID)
) ENGINE=INNODB;